"""
URLConf for Django user registration.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL begninning with
'/accounts/'.

"""

from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

#from django.contrib.auth.views import logout

from django.conf import settings
from views import activate, register
from views import adv_search, careerplus, search_result
from registration.views import *
from django.conf.urls.static import static

from jsprofile.views import UserProfileAjax
urlpatterns = patterns('',
   url(r'^recordvideo/$', recordvideo),
   #url(r'^Profile1/$', 'jsprofile.views.home',name='JobseekerHome'),
   #url(r'^ajax/$', 'jsprofile.views.ajaxview'),
   #url(r'^ajax/$', UserProfileAjax.as_view(), name='ajaxview'),

   )

urlpatterns = patterns('registration.views',   
    url(r'^RecruiterDashboard',RecruiterDashboard),
   #url(r'^RecruiterDashboard/(?P<jsjob_id>\w*)/$', RecruiterDashboardjobs),
 )
urlpatterns += patterns('',

   (r'^activate/(?P<activation_key>\w+)/$', activate),
   (r'^login/$', js_login),
   (r'^JobSeekerRegister/$', register),
   (r'^registercomplete/$', JSRegComplete),
   (r'^SearchJobs/$', adv_search),
   (r'^SearchResult/$', search_result),
   (r'^AdvSearchResult/$', advsearch_result),
   (r'^Profile/$', profile),
   (r'^Logout/$', logout_page),
   (r'^EmpLogout/$', emplogout_page),
   (r'^ProfileDetails/$', newpost),
   (r'^AddResume/$', addresume),
   (r'^Updateresume/$', Updateresume ),
   (r'^DeleteResume/(?P<res_id>\w+)/$', DeleteResume),
   (r'^resume_activation/$', resume_activation),
   (r'^EditResume/$', editresume),
   (r'^Editpersonalinfo/$', edit_personal_info),
   (r'^Editeducationinfo/$', edit_education_info),
   (r'^Editprofileinfo/$', edit_profile_info),
   (r'^Editemploymentinfo/$', edit_employment_info),
   (r'^Editprojectinfo/$', edit_project_info),
   (r'^Editotherinfo/$', edit_other_info),
   (r'^Editresumeinfo/$', edit_resume_info),
   (r'^Editprofilepicinfo/$', edit_profilepic_info),
   (r'^Editjssecurity/$',edit_jssecurity),
   #(r'^(?P<link>\w+)/$', 'RecruiterDashboard',name='RecruiterDashboard'),
   (r'^RecruiterDashboard/$', RecruiterDashboard),
   (r'^ProfileVisibility/$', visibility),
   (r'^Visibility_page/$', Visibility_page),
   (r'^MyJobs/$', MyJobs),
   (r'^JobApplySuccess/$', JobApplySuccess),
   (r'^JobFair/$', JobFair),
   (r'^Testmonial/$', Testimonial),
   (r'^Events/$', Events),
   (r'^Webinars/$', Webinars),
   (r'^JobsCity/$', JobsCity),
   (r'^JobsCompany/$', JobsCompany),
   (r'^JobsCategory/$', JobsCategory),
   (r'^JobsType/$', JobsType),
   (r'^EmpReg/$', empreg),
   (r'^EmpReg_Complete/$', empreg_complete),
   (r'^EmpActivate/$', emp_activate),
   (r'^EmpActivation/(?P<activation_key>\w+)/$', emp_activation),
   (r'^EmpLogin/$', emp_login),
   (r'^PostJob/$', jobpost),
   (r'^JobFullDescription/(?P<job_id>\w+)/$',jobfulldescription),
   (r'^CompanyList/(?P<user_id>.*)/$',companyjoblist),
   (r'^CandidateSearchResult/$',CandidateSearchResult),
   (r'^JSDetails/(?P<user_id>\w+)/$',JSDetailsbyIndividual),
   (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
   
   #JOBS
   (r'^JobsEmp/$', JobsEmp),
   (r'^JobsEmp/OpenJob/(?P<Open>\w+)/$', JobsEmp),
   (r'^JobsEmp/ExpiredJob/(?P<Expired>\w+)/$', JobsEmp),
   (r'^JobsEmp/FutureJob/(?P<Future>\w+)/$', JobsEmp),
   (r'^JobsEmp/AllJob/(?P<All>\w+)/$', JobsEmp),
     
   (r'^UpdateEmployerProfile/$',UpdateEmployerProfile),
   (r'^EmployerProfile/$',EmployerProfile),
   (r'^AddEmpGallery/$',AddEmpGallery),
   (r'^AddEmpGalleryVideo/$',AddEmpGalleryVideo),
   (r'^ViewEmpGallery/$',ViewEmpGallery),
   (r'^DeleteEmpGallery/$',DeleteEmpGallery),
   (r'^DeleteEmpGalleryVideo/$',DeleteEmpGalleryVideo),
   (r'^HotJobs/$', HotJobs),
   (r'^HotResumes/$', HotResumes),
   (r'^SecretClearedJobs/$', SecretClearedJobs),
   (r'^SecretClearedResumes/$', SecretClearedResumes),
   (r'^JobFullDescription_emp/(?P<job_id>\w+)/$',jobfulldescriptionemp),
   (r'^RecruiterChangePassword/$',RecruiterChangePassword),
   (r'^JSChangePassword/$',JSChangePassword),
   (r'^ApplyJob/(?P<job_id>\w+)/$',ApplyJob),
   (r'^Edititskillsinfo/$', edit_itskills_info),
   (r'^FAQ/$', faq),
   (r'^FAQ1/$', faq1),
   (r'^FAQ2/$', faq2),
   (r'^FAQ3/$', faq3),
   (r'^FAQ4/$', faq4),
   (r'^FAQ5/$', faq5),
   (r'^FAQ6/$', faq6),
   (r'^FAQ7/$', faq7),
   (r'^FAQ8/$', faq8),
   (r'^FAQ9/$', faq9),
   (r'^FAQ10/$', faq10),
   (r'^sitemap/$', sitemap),
   (r'^AboutUs/$', AboutUs),
   (r'^Privacy&Policy/$', PrivacyPolicy),
   (r'^TermsOfUse/$', TermsOfUse),
   (r'^Feedback/$', Feedback),
   (r'^ContactUs/$', ContactUs),
   (r'^Help/$', Help),
   (r'^TechNews/$', TechNews),
   (r'^copyright/$', copyright),
   (r'^MarketReport/$', MarketReport),
   (r'^PressRelease/$', PressRelease),
   (r'^SearchResume/$', SearchResume),
   (r'^SearchResumeAdvanced/$', SearchResumeAdvanced),
   (r'^SearchResumeAdvancedResult/$', SearchResumeAdvancedResult),
   (r'^RecruiterHome/$', RecruiterHome),
   (r'^SocialPassReset/$',SocialPassReset),
   (r'^profilepages/p(?P<num>\d{1})/$', subprofilepages),
   (r'^RecruiterFolder/(?P<fid>.*)/$', EmployerFolder),
   (r'^SearchAllJobs/$',SearchAllJobs),
   (r'^SearchAllJobsResult/$',SearchAllJobsResult),
   (r'^RecruiterDashboard/(?P<jsjob_id>\w*)/$', RecruiterDashboardjobs),
   (r'^Candidatefolder/$',Candidatefolder),
   (r'^savedsearchresult/$',savedsearchresult),
   (r'^BlogTopics/$',BlogTopic),
   (r'^Blog/(?P<btid>\w*)/$',blog),
   (r'^BlogArticle/(?P<baid>\w*)/$',blogArticle),
   (r'^BlogPost/$',blogpost),
   (r'^SaveCandidate/$',saveCandidate),
   (r'^FolderCreation/$',FolderCreation),
   (r'^ScheduleInterviewEmp/$',ScheduleInterviewEmp),
   (r'^ScheduleInterviewEmp1/$',ScheduleInterviewEmp1),
   (r'^ScheduleInterviewEmp2/$',ScheduleInterviewEmp2),
   (r'^MyInterviewZone/$',MyInterviewZone),
   (r'^RescheduleInterviewsJS/(?P<int_id>\w*)/$',RescheduleInterviewsJS),
   (r'^RescheduleInterviewsEmp/(?P<int_id>\w*)/$',RescheduleInterviewsEmp),
   (r'^JSScheduleInterview/$',JSScheduleInterview),
   (r'^EmpScheduleInterview/$',EmpScheduleInterview),
   (r'^MyInterviewZoneEmp/$',MyInterviewZoneEmp),
   (r'^InterviewConfirmJS/(?P<int_id>\w*)/$',InterviewConfirmJS),
   (r'^InterviewConfirmEmp/(?P<int_id>\w*)/$',InterviewConfirmEmp),
   (r'^CancelInterviewJS/$',CancelInterviewJS),
   (r'^CancelInterviewEmp/$',CancelInterviewEmp),
   (r'^RoundsEmp/(?P<int_id>\w*)/$',RoundsEmp),
   (r'^RoundsJS/(?P<int_id>\w*)/$',RoundsJS),
   (r'^RoundResult/$',RoundResult),
   (r'^EmpInterviewCofirmPage/$',EmpInterviewCofirmPage),
   (r'^EmpInterviewCancelPage/$',EmpInterviewCancelPage),
   (r'^EmpInterviewSuccessPage/$',EmpInterviewSuccessPage),
   (r'^EmpInterviewFailPage/$',EmpInterviewFailPage),
   (r'^JSInterviewCofirmPage/$',JSInterviewCofirmPage),
   (r'^JSInterviewSuccessPage/$',JSInterviewSuccessPage),
   (r'^JSInterviewFailPage/$',JSInterviewFailPage),
   (r'^JSInterviewCancelPage/$',JSInterviewCancelPage),
   (r'^doc/$',doc),
   (r'^EditJobPost/(?P<job_id>\w*)/$',edit_jobpost),
   (r'^RePost/(?P<job_id>\w*)/$',repost),
   (r'^DeleteJobPost/$',delete_jobpost),
   (r'^InactiveJobPost/$',inactive_jobpost),
   (r'^ActivateTodayJobPost/$',activatetoday_jobpost),
   (r'^ActiveJobPost/$',active_jobpost),
   (r'^DeleteSearchAgent/$',delete_searchagent),
   (r'^EmpPackSubscription/(?P<pck_id>\w*)/$',emp_pack_subscription),
   (r'^MyApplications/$', myapplications),
   (r'^DeleteMyApplications/$',delete_myapplications),
   (r'^ReceivedApplication/$',ReceivedApplication),
   (r'^DeleteReceivedApplication/$',DeleteReceivedApplication),
   (r'^MySearchAgents/$',MySearchAgents),
   #(r'^MyRecommendedJobs/$',MyRecommendedJobs),
   (r'^DeleteAllJSSaveJob/$',DeleteAllJSSaveJob),
   (r'^EditJSSaveJob/$',EditJSSaveJob),
   (r'^NewProfilePictures/$',NewProfilePictures),
   (r'^EmpPackname/$',emp_packname),
   (r'^EmpPackSubscription/(?P<pck_id>\w*)/$',emp_pack_subscription),
   (r'^EmpSelectedPack/$',emp_selected_pack),
   (r'^EmpSubConf/(?P<pack_id>\w*)/$',EmpSubConf),
   (r'^EditSearchAgent/$',editsearchagent),
   (r'^DeleteRecFolder/$',DeleteRecFolder),
   (r'^EditRecFolder/$',EditRecFolder),
   (r'^DelJSInsideFolder/$',DelJSInsideFolder),
   (r'^ForgotPassword/$',ForgotPassword),
   (r'^securityques/$',securityques),
   (r'^passsecurityques/$',passsecurityques),
   (r'^ForgotUsername/$',ForgotUsername),
   (r'^ForgotPasswordEmp/$',ForgotPasswordEmp),
   (r'^ForgotUsernameEmp/$',ForgotUsernameEmp),
   (r'^PasswordReset/(?P<activation_key>\w+)/$',PasswordResetActivate),
   (r'^SetNewPassword/$',SetNewPassword),
   (r'^CareerPlus/$', careerplus),
   (r'^ResumeBooster/$', resumebooster),
   (r'^ResumePlus/$', resumeplus),
   (r'^OrderSummary/(?P<pck_id>\w*)/$', ordersummary),
   (r'^DeleteVideoResume/(?P<vs_id>\w*)/$', DeleteVideoResume),
   (r'^EmpResumeComp/$',emprescomp),
   (r'^emprescompdoc/(?P<res_id>\w*)/$', emprescompdoc),
   (r'^empdoc/(?P<userjs_id>\w*)/$', empdoc),
   (r'^sociallogin/$', createnew),
   (r'^Miles/$', miles),
   (r'^videorecording/$', videorecording),
   (r'^ActivateJob/$', ActivateJob),
   (r'^SelectPack/$', SelectPack),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
